export default {
  products: [
    {
      _id: "1",
      name: "slim shirt",
      category: "shirts",
      image: "/images/pic3.jpg",
      price: 300000,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "2",
      name: "Fit shirt",
      category: "shirts",
      image: "/images/pic3.jpg",
      price: 93000,
      brand: "Nike",
      rating: 4.3,
      numReviews: 3,
      countInStock: 6,
    },
    {
      _id: "3",
      name: "Best pants",
      category: "shirts",
      image: "/images/pic3.jpg",
      price: 80000,
      brand: "Nike",
      rating: 2.5,
      numReviews: 7,
    },
    {
      _id: "4",
      name: "Best pants",
      category: "shirts",
      image: "/images/pic3.jpg",
      price: 80000,
      brand: "Nike",
      rating: 2.5,
      numReviews: 7,
      countInStock: 0,
    },
    {
      _id: "5",
      name: "Best pants",
      category: "shirts",
      image: "/images/pic3.jpg",
      price: 80000,
      brand: "Nike",
      rating: 2.5,
      numReviews: 7,
      countInStock: 6,
    },
    {
      _id: "6",
      name: "Best pants",
      category: "shirts",
      image: "/images/pic3.jpg",
      price: 80000,
      brand: "Nike",
      rating: 2.5,
      numReviews: 7,
    },
  ],
};
